### ISSUE TITLE
static variables in key.c don't have __thread attribute

### ISSUE THREAD

**Issue by michaeltalyansky** [toffaletti/state-threads#1]
Probably forgotten: results in multiple worker pthreads sharing key counters. Cured with this simple patch:

diff --git a/key.c b/key.c
index 9708c35..9133e65 100644
--- a/key.c
+++ b/key.c
@@ -47,8 +47,8 @@
 /*
- Destructor table for per-thread private data
  */
  -static _st_destructor_t _st_destructors[ST_KEYS_MAX];
  -static int key_max = 0;
  +static __thread _st_destructor_t _st_destructors[ST_KEYS_MAX];
  +static __thread int key_max = 0;

**Comment by toffaletti** [comment]
Fixed by #2 thanks.
